import { Footer } from "@/components/Footer/Footer";
import "./globals.css";
import { Inter } from "next/font/google";
import { Header } from "@/components/Header/Header";
import { Providers } from "@/components/Providers/Providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`wrapper ${inter.className}`}>
        <Providers>
          <Header />
          <main className="container"> {children}</main>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
